### ISSUE TITLE
Invalid workflow file

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#43]
Ik krijg bij poging een publicatie aan te passen, met enkel een wijziging in een markdown file een onverwachte fout en krijg er geen vinger achter wat hier aan de hand is.

Link naar de [gefaalde workflow](https://github.com/MinBZK/wetsuitvoering/actions/runs/13388648177)

![Image](https://github.com/user-attachments/assets/7141be64-f81f-4063-abe0-551103e1b456)

**Comment by TimvdLippe** [comment]
Op basis van https://github.com/orgs/community/discussions/76409 zijn er meerdere opties:

1. Op https://github.com/MinBZK/wetsuitvoering/settings/actions bij "Workflow permissions" moet "Read and write permissions" aan staan
2. Het zou ook kunnen dat dit op GitHub organisation niveau moet worden gefixt: https://github.com/organizations/MinBZK/settings/actions
3. De oplossing uit https://github.com/orgs/community/discussions/76409#discussioncomment-11260212
```
jobs:
  call-workflow:
    permissions:
      id-token: write
  publish:
    needs: build
    name: Publish (Logius)
    uses: Logius-standaarden/Automatisering/.github/workflows/publish.yml@main
    secrets: inherit
```

Werkt een van deze opties?
